services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: db_password_1234
      POSTGRES_USER: admin
      POSTGRES_DB: emarkdb
    ports:
      - "5431:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
