import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Emark</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href={"/sign-in"}>Sign in</Link>
      <Link href={"/sign-up"}>Sign up</Link>
      Index
    </>
  );
};

export default Home;
